### ISSUE TITLE
Update for ydns.io

### ISSUE THREAD

**Issue by cl0rm** [wyattjoh/ydns-updater#2]
They seem to have changed from ydns.eu to ydns.io.

Currently without modifications I get:
Cannot perform http get:Get "https://ydns.eu/api/v1/update/?host=HOST.ydns.eu": x509: certificate is valid for ydns.io, not ydns.eu

**Comment by wyattjoh** [comment]
This should be fixed in https://github.com/wyattjoh/ydns-updater/releases/tag/v2.0.0!

Thank you!
